java -cp ../../mips_16/sw/ mips_16_assembler ../../bench/top/testcases/hazard_r0.asm ../../bench/top/testcases/hazard_r0.prog
java -cp ../../mips_16/sw/ mips_16_assembler ../../bench/top/testcases/hazard_r1.asm ../../bench/top/testcases/hazard_r1.prog
java -cp ../../mips_16/sw/ mips_16_assembler ../../bench/top/testcases/hazard_r2.asm ../../bench/top/testcases/hazard_r2.prog
java -cp ../../mips_16/sw/ mips_16_assembler ../../bench/top/testcases/hazard_r3.asm ../../bench/top/testcases/hazard_r3.prog
java -cp ../../mips_16/sw/ mips_16_assembler ../../bench/top/testcases/hazard_r4.asm ../../bench/top/testcases/hazard_r4.prog
java -cp ../../mips_16/sw/ mips_16_assembler ../../bench/top/testcases/hazard_r5.asm ../../bench/top/testcases/hazard_r5.prog
java -cp ../../mips_16/sw/ mips_16_assembler ../../bench/top/testcases/hazard_r6.asm ../../bench/top/testcases/hazard_r6.prog
java -cp ../../mips_16/sw/ mips_16_assembler ../../bench/top/testcases/hazard_r7.asm ../../bench/top/testcases/hazard_r7.prog
java -cp ../../mips_16/sw/ mips_16_assembler ../../bench/top/testcases/hazard_detection.asm ../../bench/top/testcases/hazard_detection.prog
java -cp ../../mips_16/sw/ mips_16_assembler ../../bench/top/testcases/add.asm ../../bench/top/testcases/add.prog
java -cp ../../mips_16/sw/ mips_16_assembler ../../bench/top/testcases/addi.asm ../../bench/top/testcases/addi.prog
java -cp ../../mips_16/sw/ mips_16_assembler ../../bench/top/testcases/and.asm ../../bench/top/testcases/and.prog
java -cp ../../mips_16/sw/ mips_16_assembler ../../bench/top/testcases/or.asm ../../bench/top/testcases/or.prog
java -cp ../../mips_16/sw/ mips_16_assembler ../../bench/top/testcases/sl.asm ../../bench/top/testcases/sl.prog
java -cp ../../mips_16/sw/ mips_16_assembler ../../bench/top/testcases/sr.asm ../../bench/top/testcases/sr.prog
java -cp ../../mips_16/sw/ mips_16_assembler ../../bench/top/testcases/sru.asm ../../bench/top/testcases/sru.prog
java -cp ../../mips_16/sw/ mips_16_assembler ../../bench/top/testcases/sub.asm ../../bench/top/testcases/sub.prog
java -cp ../../mips_16/sw/ mips_16_assembler ../../bench/top/testcases/R0_load.asm ../../bench/top/testcases/R0_load.prog
java -cp ../../mips_16/sw/ mips_16_assembler ../../bench/top/testcases/R1_load_store.asm ../../bench/top/testcases/R1_load_store.prog
java -cp ../../mips_16/sw/ mips_16_assembler ../../bench/top/testcases/R2_load_store.asm ../../bench/top/testcases/R2_load_store.prog
java -cp ../../mips_16/sw/ mips_16_assembler ../../bench/top/testcases/R3_load_store.asm ../../bench/top/testcases/R3_load_store.prog
java -cp ../../mips_16/sw/ mips_16_assembler ../../bench/top/testcases/R4_load_store.asm ../../bench/top/testcases/R4_load_store.prog
java -cp ../../mips_16/sw/ mips_16_assembler ../../bench/top/testcases/R5_load_store.asm ../../bench/top/testcases/R5_load_store.prog
java -cp ../../mips_16/sw/ mips_16_assembler ../../bench/top/testcases/R6_load_store.asm ../../bench/top/testcases/R6_load_store.prog
java -cp ../../mips_16/sw/ mips_16_assembler ../../bench/top/testcases/R7_load_store.asm ../../bench/top/testcases/R7_load_store.prog
java -cp ../../mips_16/sw/ mips_16_assembler ../../bench/top/testcases/xor.asm ../../bench/top/testcases/xor.prog
java -cp ../../mips_16/sw/ mips_16_assembler ../../bench/top/testcases/branch_taken.asm ../../bench/top/testcases/branch_taken.prog
java -cp ../../mips_16/sw/ mips_16_assembler ../../bench/top/testcases/branch_not_taken.asm ../../bench/top/testcases/branch_not_taken.prog
java -cp ../../mips_16/sw/ mips_16_assembler ../../bench/top/testcases/nop.asm ../../bench/top/testcases/nop.prog
